// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	esSyncExecutionLogFieldNames          = builder.RawFieldNames(&EsSyncExecutionLog{})
	esSyncExecutionLogRows                = strings.Join(esSyncExecutionLogFieldNames, ",")
	esSyncExecutionLogRowsExpectAutoSet   = strings.Join(stringx.Remove(esSyncExecutionLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	esSyncExecutionLogRowsWithPlaceHolder = strings.Join(stringx.Remove(esSyncExecutionLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	esSyncExecutionLogModel interface {
		Insert(ctx context.Context, data *EsSyncExecutionLog) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*EsSyncExecutionLog, error)
		Update(ctx context.Context, data *EsSyncExecutionLog) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultEsSyncExecutionLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	EsSyncExecutionLog struct {
		Id              uint64         `db:"id"`
		TaskId          uint64         `db:"task_id"`           // 任务配置ID
		TaskName        string         `db:"task_name"`         // 任务名称
		ExecutionTime   time.Time      `db:"execution_time"`    // 执行时间
		ExecutionStatus string         `db:"execution_status"`  // 执行状态(success/failed/partial)
		TotalHosts      int64          `db:"total_hosts"`       // 总主机数
		SuccessCount    int64          `db:"success_count"`     // 成功同步数量
		FailedCount     int64          `db:"failed_count"`      // 失败同步数量
		NotInPoolCount  int64          `db:"not_in_pool_count"` // ES有但hosts_pool没有的数量
		ErrorMessage    sql.NullString `db:"error_message"`     // 错误信息
		DurationMs      sql.NullInt64  `db:"duration_ms"`       // 执行时长(毫秒)
		QueryTimeRange  sql.NullString `db:"query_time_range"`  // 查询时间范围
		CreatedAt       time.Time      `db:"created_at"`        // 创建时间
	}
)

func newEsSyncExecutionLogModel(conn sqlx.SqlConn) *defaultEsSyncExecutionLogModel {
	return &defaultEsSyncExecutionLogModel{
		conn:  conn,
		table: "`es_sync_execution_log`",
	}
}

func (m *defaultEsSyncExecutionLogModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEsSyncExecutionLogModel) FindOne(ctx context.Context, id uint64) (*EsSyncExecutionLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", esSyncExecutionLogRows, m.table)
	var resp EsSyncExecutionLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEsSyncExecutionLogModel) Insert(ctx context.Context, data *EsSyncExecutionLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, esSyncExecutionLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TaskId, data.TaskName, data.ExecutionTime, data.ExecutionStatus, data.TotalHosts, data.SuccessCount, data.FailedCount, data.NotInPoolCount, data.ErrorMessage, data.DurationMs, data.QueryTimeRange)
	return ret, err
}

func (m *defaultEsSyncExecutionLogModel) Update(ctx context.Context, data *EsSyncExecutionLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, esSyncExecutionLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TaskId, data.TaskName, data.ExecutionTime, data.ExecutionStatus, data.TotalHosts, data.SuccessCount, data.FailedCount, data.NotInPoolCount, data.ErrorMessage, data.DurationMs, data.QueryTimeRange, data.Id)
	return err
}

func (m *defaultEsSyncExecutionLogModel) tableName() string {
	return m.table
}
