// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	esSyncTaskConfigFieldNames          = builder.RawFieldNames(&EsSyncTaskConfig{})
	esSyncTaskConfigRows                = strings.Join(esSyncTaskConfigFieldNames, ",")
	esSyncTaskConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(esSyncTaskConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	esSyncTaskConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(esSyncTaskConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	esSyncTaskConfigModel interface {
		Insert(ctx context.Context, data *EsSyncTaskConfig) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*EsSyncTaskConfig, error)
		FindOneByTaskName(ctx context.Context, taskName string) (*EsSyncTaskConfig, error)
		Update(ctx context.Context, data *EsSyncTaskConfig) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultEsSyncTaskConfigModel struct {
		conn  sqlx.SqlConn
		table string
	}

	EsSyncTaskConfig struct {
		Id                uint64         `db:"id"`
		TaskName          string         `db:"task_name"`           // 任务名称
		Description       sql.NullString `db:"description"`         // 任务描述
		EsEndpoint        string         `db:"es_endpoint"`         // ES接口地址
		EsIndexPattern    string         `db:"es_index_pattern"`    // ES索引模式
		CronExpression    string         `db:"cron_expression"`     // Cron表达式
		QueryTimeRange    string         `db:"query_time_range"`    // 查询时间范围(如7d,30d)
		IsEnabled         int64          `db:"is_enabled"`          // 是否启用
		CreatedBy         sql.NullString `db:"created_by"`          // 创建者
		LastExecutionTime sql.NullTime   `db:"last_execution_time"` // 上次执行时间
		NextExecutionTime sql.NullTime   `db:"next_execution_time"` // 下次执行时间
		CreatedAt         time.Time      `db:"created_at"`          // 创建时间
		UpdatedAt         time.Time      `db:"updated_at"`          // 更新时间
		DeletedAt         sql.NullTime   `db:"deleted_at"`          // 删除时间
	}
)

func newEsSyncTaskConfigModel(conn sqlx.SqlConn) *defaultEsSyncTaskConfigModel {
	return &defaultEsSyncTaskConfigModel{
		conn:  conn,
		table: "`es_sync_task_config`",
	}
}

func (m *defaultEsSyncTaskConfigModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEsSyncTaskConfigModel) FindOne(ctx context.Context, id uint64) (*EsSyncTaskConfig, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", esSyncTaskConfigRows, m.table)
	var resp EsSyncTaskConfig
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEsSyncTaskConfigModel) FindOneByTaskName(ctx context.Context, taskName string) (*EsSyncTaskConfig, error) {
	var resp EsSyncTaskConfig
	query := fmt.Sprintf("select %s from %s where `task_name` = ? limit 1", esSyncTaskConfigRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, taskName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEsSyncTaskConfigModel) Insert(ctx context.Context, data *EsSyncTaskConfig) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, esSyncTaskConfigRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TaskName, data.Description, data.EsEndpoint, data.EsIndexPattern, data.CronExpression, data.QueryTimeRange, data.IsEnabled, data.CreatedBy, data.LastExecutionTime, data.NextExecutionTime, data.DeletedAt)
	return ret, err
}

func (m *defaultEsSyncTaskConfigModel) Update(ctx context.Context, newData *EsSyncTaskConfig) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, esSyncTaskConfigRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TaskName, newData.Description, newData.EsEndpoint, newData.EsIndexPattern, newData.CronExpression, newData.QueryTimeRange, newData.IsEnabled, newData.CreatedBy, newData.LastExecutionTime, newData.NextExecutionTime, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultEsSyncTaskConfigModel) tableName() string {
	return m.table
}
