// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	goldendbClusterInstanceFieldNames          = builder.RawFieldNames(&GoldendbClusterInstance{})
	goldendbClusterInstanceRows                = strings.Join(goldendbClusterInstanceFieldNames, ",")
	goldendbClusterInstanceRowsExpectAutoSet   = strings.Join(stringx.Remove(goldendbClusterInstanceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	goldendbClusterInstanceRowsWithPlaceHolder = strings.Join(stringx.Remove(goldendbClusterInstanceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	goldendbClusterInstanceModel interface {
		Insert(ctx context.Context, data *GoldendbClusterInstance) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*GoldendbClusterInstance, error)
		FindOneByClusterNameIpPort(ctx context.Context, clusterName string, ip string, port int64) (*GoldendbClusterInstance, error)
		Update(ctx context.Context, data *GoldendbClusterInstance) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultGoldendbClusterInstanceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GoldendbClusterInstance struct {
		Id             uint64         `db:"id"`
		ClusterName    string         `db:"cluster_name"`    // 集群名称
		Ip             string         `db:"ip"`              // 实例IP
		Port           int64          `db:"port"`            // 实例端口
		InstanceRole   string         `db:"instance_role"`   // 实例角色(primary/secondary)
		Version        sql.NullString `db:"version"`         // GoldenDB版本
		InstanceStatus string         `db:"instance_status"` // 实例状态
		DataDir        sql.NullString `db:"data_dir"`        // 数据目录
		CreatedAt      time.Time      `db:"created_at"`
		UpdatedAt      time.Time      `db:"updated_at"`
		DeletedAt      sql.NullTime   `db:"deleted_at"`
	}
)

func newGoldendbClusterInstanceModel(conn sqlx.SqlConn) *defaultGoldendbClusterInstanceModel {
	return &defaultGoldendbClusterInstanceModel{
		conn:  conn,
		table: "`goldendb_cluster_instance`",
	}
}

func (m *defaultGoldendbClusterInstanceModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGoldendbClusterInstanceModel) FindOne(ctx context.Context, id uint64) (*GoldendbClusterInstance, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", goldendbClusterInstanceRows, m.table)
	var resp GoldendbClusterInstance
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGoldendbClusterInstanceModel) FindOneByClusterNameIpPort(ctx context.Context, clusterName string, ip string, port int64) (*GoldendbClusterInstance, error) {
	var resp GoldendbClusterInstance
	query := fmt.Sprintf("select %s from %s where `cluster_name` = ? and `ip` = ? and `port` = ? limit 1", goldendbClusterInstanceRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, clusterName, ip, port)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGoldendbClusterInstanceModel) Insert(ctx context.Context, data *GoldendbClusterInstance) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, goldendbClusterInstanceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClusterName, data.Ip, data.Port, data.InstanceRole, data.Version, data.InstanceStatus, data.DataDir, data.DeletedAt)
	return ret, err
}

func (m *defaultGoldendbClusterInstanceModel) Update(ctx context.Context, newData *GoldendbClusterInstance) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, goldendbClusterInstanceRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClusterName, newData.Ip, newData.Port, newData.InstanceRole, newData.Version, newData.InstanceStatus, newData.DataDir, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultGoldendbClusterInstanceModel) tableName() string {
	return m.table
}
