// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mssqlClusterInstanceFieldNames          = builder.RawFieldNames(&MssqlClusterInstance{})
	mssqlClusterInstanceRows                = strings.Join(mssqlClusterInstanceFieldNames, ",")
	mssqlClusterInstanceRowsExpectAutoSet   = strings.Join(stringx.Remove(mssqlClusterInstanceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mssqlClusterInstanceRowsWithPlaceHolder = strings.Join(stringx.Remove(mssqlClusterInstanceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	mssqlClusterInstanceModel interface {
		Insert(ctx context.Context, data *MssqlClusterInstance) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MssqlClusterInstance, error)
		FindOneByClusterNameIpInstancePort(ctx context.Context, clusterName string, ip string, instancePort int64) (*MssqlClusterInstance, error)
		Update(ctx context.Context, data *MssqlClusterInstance) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMssqlClusterInstanceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MssqlClusterInstance struct {
		Id             uint64         `db:"id"`
		ClusterName    string         `db:"cluster_name"`    // 集群名称
		Ip             string         `db:"ip"`              // 实例IP
		InstancePort   int64          `db:"instance_port"`   // 实例端口
		InstanceRole   string         `db:"instance_role"`   // 实例角色(primary/secondary)
		Version        sql.NullString `db:"version"`         // MSSQL版本
		InstanceStatus string         `db:"instance_status"` // 实例状态
		DataDir        sql.NullString `db:"data_dir"`        // 数据目录
		CreatedAt      time.Time      `db:"created_at"`
		UpdatedAt      time.Time      `db:"updated_at"`
		DeletedAt      sql.NullTime   `db:"deleted_at"`
	}
)

func newMssqlClusterInstanceModel(conn sqlx.SqlConn) *defaultMssqlClusterInstanceModel {
	return &defaultMssqlClusterInstanceModel{
		conn:  conn,
		table: "`mssql_cluster_instance`",
	}
}

func (m *defaultMssqlClusterInstanceModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMssqlClusterInstanceModel) FindOne(ctx context.Context, id uint64) (*MssqlClusterInstance, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mssqlClusterInstanceRows, m.table)
	var resp MssqlClusterInstance
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMssqlClusterInstanceModel) FindOneByClusterNameIpInstancePort(ctx context.Context, clusterName string, ip string, instancePort int64) (*MssqlClusterInstance, error) {
	var resp MssqlClusterInstance
	query := fmt.Sprintf("select %s from %s where `cluster_name` = ? and `ip` = ? and `instance_port` = ? limit 1", mssqlClusterInstanceRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, clusterName, ip, instancePort)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMssqlClusterInstanceModel) Insert(ctx context.Context, data *MssqlClusterInstance) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, mssqlClusterInstanceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClusterName, data.Ip, data.InstancePort, data.InstanceRole, data.Version, data.InstanceStatus, data.DataDir, data.DeletedAt)
	return ret, err
}

func (m *defaultMssqlClusterInstanceModel) Update(ctx context.Context, newData *MssqlClusterInstance) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mssqlClusterInstanceRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClusterName, newData.Ip, newData.InstancePort, newData.InstanceRole, newData.Version, newData.InstanceStatus, newData.DataDir, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultMssqlClusterInstanceModel) tableName() string {
	return m.table
}
