// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	"cmdb-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/auth/cas",
				Handler: CASLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/logout",
				Handler: LogoutHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/auth/userinfo",
					Handler: UserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/add_hosts_application",
					Handler: AddHostsApplicationHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/analyze_resource_usage",
					Handler: AnalyzeResourceUsageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/auto-fetch-host-info",
					Handler: AutoFetchHostInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/backup-restore-check-info",
					Handler: GetBackupRestoreCheckInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/cluster-confirm-summary",
					Handler: GetClusterConfirmSummaryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/cluster-group-report",
					Handler: GenerateClusterGroupReportHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/cluster-groups",
					Handler: GetClusterGroupsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/cluster-resource-summary",
					Handler: GetClusterResourceSummaryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/cluster-resource-usage",
					Handler: GetClusterResourceUsageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/cluster-resources",
					Handler: GetClusterResourcesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/cluster-resources-max",
					Handler: GetClusterResourcesMaxHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/collect_applications",
					Handler: CollectApplicationsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/cmdb/v1/delete_hosts_application",
					Handler: DeleteHostsApplicationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/disk-full-prediction",
					Handler: GetDiskFullPredictionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/disk-prediction",
					Handler: GetDiskPredictionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/external-sync-execute",
					Handler: ExecuteExternalSyncHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/external-sync-execute-file",
					Handler: ExecuteExternalSyncByFileHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/external-sync-execution-detail/:execution_id",
					Handler: GetExternalSyncExecutionDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/external-sync-execution-logs",
					Handler: GetExternalSyncExecutionLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/external-sync-full-sync",
					Handler: ExecuteExternalSyncFullSyncHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/external-sync-tasks",
					Handler: CreateExternalSyncTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/external-sync-tasks",
					Handler: GetExternalSyncTasksHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/cmdb/v1/external-sync-tasks/:task_id",
					Handler: UpdateExternalSyncTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/cmdb/v1/external-sync-tasks/:task_id",
					Handler: DeleteExternalSyncTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/external-sync-tasks/:task_id",
					Handler: GetExternalSyncTaskDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/cmdb/v1/external-sync-tasks/enable",
					Handler: EnableExternalSyncTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/fetch-hosts-hardware-info",
					Handler: FetchHostsHardwareInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/generate-and-send-report",
					Handler: GenerateAndSendReportHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/get_cluster_usage",
					Handler: GetClusterUsageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/get_host_detail/:id",
					Handler: GetHostDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/get_hosts_pool_detail",
					Handler: GetHostsPoolDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/hardware-resource-verification",
					Handler: HardwareResourceVerificationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/hardware-resource-verification-history",
					Handler: GetHardwareResourceVerificationHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/hardware-resource-verification-status",
					Handler: GetHardwareResourceVerificationStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/idc-list",
					Handler: GetIdcListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/idc-report",
					Handler: GenerateIDCReportHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/insert-server-resource",
					Handler: InsertServerResourceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/load-server-metrics-csv",
					Handler: LoadServerMetricsCSVHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/manual-add-host",
					Handler: ManualAddHostHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/cmdb/v1/modify_hosts_application",
					Handler: ModifyHostsApplicationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/resource-alerts",
					Handler: GetResourceAlertsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/scheduled-tasks",
					Handler: CreateScheduledTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/scheduled-tasks",
					Handler: GetScheduledTasksHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/cmdb/v1/scheduled-tasks/:id",
					Handler: UpdateScheduledTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/cmdb/v1/scheduled-tasks/:id",
					Handler: DeleteScheduledTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/cmdb/v1/scheduled-tasks/enable",
					Handler: EnableScheduledTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/scheduled-tasks/execution-details/:execution_task_id",
					Handler: GetScheduledTaskExecutionDetailsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/scheduled-tasks/execution-history",
					Handler: GetScheduledTaskExecutionHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/send-email",
					Handler: SendEmailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/server-metrics-csv-progress",
					Handler: GetServerMetricsCSVProgressHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/server-resources",
					Handler: GetServerResourcesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cmdb/v1/server-resources-max",
					Handler: GetServerResourcesMaxHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/sync-cluster-groups",
					Handler: SyncClusterGroupsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/sync-external-cmdb",
					Handler: SyncExternalCmdbHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/sync-hosts-from-clusters",
					Handler: SyncHostsFromClustersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/trigger-report",
					Handler: TriggerReportHandler(serverCtx),
				},
				{
					Method:  http.MethodOptions,
					Path:    "/api/cmdb/v1/verify-monitoring-data",
					Handler: VerifyMonitoringDataOptionsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cmdb/v1/verify-monitoring-data",
					Handler: VerifyMonitoringDataHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/platform/cmsys/auth",
				Handler: MockCMSysAuthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/platform/cmsys/data",
				Handler: MockCMSysDataHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/platform/cmsys/data-by-ips",
				Handler: MockCMSysDataByIPsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/platform/query/es",
				Handler: MockEsQueryHandler(serverCtx),
			},
		},
	)
}
